name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ravitejakamalapuram/.github-workflows-shared/.github/workflows/android-cd.yml@v1.1.10
    with:
      runner-type: 'self-hosted'
      java-version: '17'
      package-name: 'com.carfry369.teleport'
      deploy-to-play: true
      include-extension: true
      extension-dir: 'chrome-extension'
    secrets:
      release-keystore-base64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
      keystore-password: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      key-alias: ${{ secrets.RELEASE_KEY_ALIAS }}
      key-password: ${{ secrets.RELEASE_KEY_PASSWORD }}
      play-service-account-key: ${{ secrets.PLAY_SERVICE_ACCOUNT_KEY }}
