name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ravitejakamalapuram/.github-workflows-shared/.github/workflows/android-ci.yml@v1.1.2
    with:
      java-version: '17'
      run-tests: true
      validate-extension: true
      extension-dir: 'chrome-extension'
